name: NPCTeams
version: '1.0-SNAPSHOT'
main: br.com.PluginVideo
api-version: '1.21'
depend: [Citizens, Sentinel]
commands:
  spawnteams:
    description: Spawna duas equipes de NPCs que brigam entre si
    usage: /spawnteams [localização]